# ~/.ticker.yaml
show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 5
currency: EUR
currency-summary-only: false
watchlist:
  - VWCE.DE
  - IWDA.AS
  - GME
  - BTC-USD
  - ETH-USD
# lots:
#   - symbol: "ABNB"
#     quantity: 35.0
#     unit_cost: 146.00
#   - symbol: "ARKW"
#     quantity: 20.0
#     unit_cost: 152.25
#   - symbol: "ARKW"
#     quantity: 20.0
#     unit_cost: 145.35
#     fixed_cost: 7.00 # e.g. brokerage commission fee
# groups:
#   - name: ETF
#     watchlist:
#       - VWCE.DE
#       - IWDA.AS
#   - name: stonks 
#     watchlist:
#       - GME 
#   - name: crypto
#     watchlist:
#       - BTC-USD
#       - ETH-USD
    # holdings:
    #   - symbol: SOL1-USD
    #     quantity: 17
    #     unit_cost: 159.10

